language: csharp
mono: none
solution: Binance.Net.sln
dotnet: 2.0.0
dist: xenial
script:
 - dotnet build Binance.Net/Binance.Net.csproj --framework "netstandard2.0"
 - dotnet test Binance.Net.UnitTests/Binance.Net.UnitTests.csproj
